/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zed.aplicacao;

import com.zed.banco.ContaCorrente;
import com.zed.banco.ContaPoupanca;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author arrud
 */
public class BancoForm extends javax.swing.JFrame {

    private static Set<JMenuItem> itens = new HashSet<>();
    /**
     * Creates new form BancoForm
     */
    public BancoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConta = new javax.swing.JMenu();
        menuItemPoupanca = new javax.swing.JRadioButtonMenuItem();
        menuItemCorrente = new javax.swing.JRadioButtonMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        menuConta.setText("Contas");

        menuItemPoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuItemPoupanca.setSelected(true);
        menuItemPoupanca.setText("Conta Poupança");
        menuItemPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPoupancaActionPerformed(evt);
            }
        });
        menuConta.add(menuItemPoupanca);

        menuItemCorrente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCorrente.setSelected(true);
        menuItemCorrente.setText("Conta Corrente");
        menuItemCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCorrenteActionPerformed(evt);
            }
        });
        menuConta.add(menuItemCorrente);

        jMenuBar1.add(menuConta);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areaTrabalho)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areaTrabalho)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuItemCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCorrenteActionPerformed
        ContaForm conta = new ContaForm(new ContaCorrente());
        if (menuItemCorrente.isEnabled()) {
            areaTrabalho.add(conta);
            conta.setLegenda("Corrente");
            conta.setVisible(true);
        }
        desabilitarItens(menuItemCorrente,menuItemPoupanca);
    }//GEN-LAST:event_menuItemCorrenteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        itens.addAll(Arrays.asList(menuItemCorrente,menuItemPoupanca));
    }//GEN-LAST:event_formWindowOpened

    private void menuItemPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPoupancaActionPerformed
        ContaForm conta = new ContaForm(new ContaPoupanca());
        if (menuItemPoupanca.isEnabled()) {
            areaTrabalho.add(conta);
            conta.setLegenda("Poupança");
            conta.setVisible(true);
        }
        desabilitarItens(menuItemCorrente,menuItemPoupanca);
    }//GEN-LAST:event_menuItemPoupancaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConta;
    private javax.swing.JRadioButtonMenuItem menuItemCorrente;
    private javax.swing.JRadioButtonMenuItem menuItemPoupanca;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

    private void desabilitarItens(JMenuItem... itens) {
        for (JMenuItem item : itens) {
            item.setEnabled(false);
        }
    }
    protected static void habilitarItens() {
        itens.stream().filter(i -> !i.isEnabled()).forEach(i -> i.setEnabled(true));
    }
}
